spring:
  application:
    name: book-svc
  cloud:
    services:
      registrationMethod: direct
          
management:
  security:
    enabled: false

security:
  basic:
    enabled: false
        
feign:
  hystrix:
    enabled: true

logging.level.pivotal.io.booksvc: DEBUG
